name: PR Status Check

on: 
  pull_request:
    branches:
      - main

jobs:
  PR_Status_Check:   # Match the branch rule exactly here
    runs-on: ubuntu-latest
    steps:
      - name: Run Status Check
        run: echo "Status Check Passed"
